cars/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('post_link/', views.postView, name='posts'),
]

custom_users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('registration/', views.RegistrationView.as_view()),
    path('login/', views.AuthLoginView.as_view(), name='home'),
    path('logout/', views.AuthLogoutView.as_view(), name='logout'),
    path('homepage/', views.UserListView.as_view(), name='post'),
    path('staff_image/', views.staffView, name='staff'),
]

main/main/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = ([
                path('admin/', admin.site.urls),
                path('', include('cars.urls')),
                path('', include('auto_parts_store.urls')),
                path('', include('parser_app.urls')),
                path('', include('custom_users.urls')),
                path('', include('cloth.urls')),
            ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
            + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

templates/users/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Пользователи</title>
</head>
<body background="/static/photo/fon3.jpg">
<h1>
    <center>Список пользователей</center>
</h1>
<ol>
    {% for i in object_list %}
    <li>
        <h2>{{i.username}}</h2> - <em>{{i.email}}</em>
    </li>
    {% endfor %}
    {% for i in staff_value %}
    <h1 class="title">{{i.name}}</h1>
    <img src="{{i.image.url}}" class="card-img-top" alt="...">
    {% endfor %}
    <form action="{% url 'users:logout' %}">
        {% csrf_token %}
        <button type="submit" >Выйти из аккаунта</button>
    </form>
<h2><a href="/staff_image/">Лучшие сотрудники</a></h2>
</ol>
</body>
</html>

templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Авторизация</title>
</head>
<body background="/static/photo/fon3.jpg">
<h1>Введите данные для входа</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Войти</button>
    <button><a href="/registration/">Регистрация</a></button>
</form>
</body>
</html>

templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
</head>
<body background="/static/photo/fon3.jpg">
<center>
    <h1>Заполните поля</h1>
</center>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Регистрация</button>
</form>
</body>
</html>

templates/users/staff.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Лучшие сотрудники</title>
</head>
<body background="/static/photo/fon3.jpg">
<h1>
    <center>Фото лучших сотрудников</center>
</h1>
<ol>
    {% for i in post_key %}
    <h1 class="title">{{i.name}}</h1>
    <img src="{{i.image.url}}" class="card-img-top">
    {% endfor %}
    <form action="{% url 'users:post' %}">
        {% csrf_token %}
        <button type="submit" >Назад</button>
    </form>
</ol>
</body>
</html>